id = "ansible-lens"
name = "Ansible Lens"
version = "0.2.2"
schema_version = 1
authors = ["Jan Krüger <jan@krueger-jan.de>"]
description = "Go to Definition for nested Ansible/Jinja2 variables"
repository = "https://github.com/jan-krueger/ansible-lens"

[language_servers.ansible-lens]
name = "Ansible Lens"
languages = ["YAML", "Ansible", "Jinja2"]
